version: '2.3'

services:
  database:
    container_name: rmbg-restapi_database
    image: mysql:8.0.21
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - docker/database.env
    restart: always
    expose:
      - 3306
    ports:
      - "33306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
  rabbitmq:
    container_name: rmbg-restapi_rabbitmq
    image: rabbitmq:3.8-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=mqadmin
      - RABBITMQ_DEFAULT_PASS=mqpwdpwd
    expose:
      - 5672
    ports:
      - "35672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 3s
      retries: 10
  redis:
    container_name: rmbg-restapi_redis
    image: redis:5.0-alpine
    restart: always
    expose:
      - 6379
    ports:
      - "36379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 3s
      retries: 10
  main:
    container_name: rmbg-restapi_django
    build:
      context: ./
      dockerfile: docker/Dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/main.env"
      - "docker/database.env"
    links:
      - database
      - redis
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    expose:
      - 8000
      - 22
    volumes:
      - ./media:/workspace/media
    ports:
      - "58888:8000"
      - "50022:22"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
